package graph

import (
	"github.com/freightcms/locations/models"
	"github.com/graphql-go/graphql"
)

var CountryCodeType = graphql.NewEnum(
	graphql.EnumConfig{
		Name: "CountryCode",
		Values: graphql.EnumValueConfigMap{
			"AD": &graphql.EnumValueConfig{Value: models.AD},
			"AE": &graphql.EnumValueConfig{Value: models.AE},
			"AF": &graphql.EnumValueConfig{Value: models.AF},
			"AG": &graphql.EnumValueConfig{Value: models.AG},
			"AI": &graphql.EnumValueConfig{Value: models.AI},
			"AL": &graphql.EnumValueConfig{Value: models.AL},
			"AM": &graphql.EnumValueConfig{Value: models.AM},
			"AO": &graphql.EnumValueConfig{Value: models.AO},
			"AR": &graphql.EnumValueConfig{Value: models.AR},
			"AS": &graphql.EnumValueConfig{Value: models.AS},
			"AT": &graphql.EnumValueConfig{Value: models.AT},
			"AU": &graphql.EnumValueConfig{Value: models.AU},
			"AW": &graphql.EnumValueConfig{Value: models.AW},
			"AX": &graphql.EnumValueConfig{Value: models.AX},
			"AZ": &graphql.EnumValueConfig{Value: models.AZ},
			"BA": &graphql.EnumValueConfig{Value: models.BA},
			"BB": &graphql.EnumValueConfig{Value: models.BB},
			"BD": &graphql.EnumValueConfig{Value: models.BD},
			"BE": &graphql.EnumValueConfig{Value: models.BE},
			"BF": &graphql.EnumValueConfig{Value: models.BF},
			"BG": &graphql.EnumValueConfig{Value: models.BG},
			"BH": &graphql.EnumValueConfig{Value: models.BH},
			"BI": &graphql.EnumValueConfig{Value: models.BI},
			"BJ": &graphql.EnumValueConfig{Value: models.BJ},
			"BL": &graphql.EnumValueConfig{Value: models.BL},
			"BM": &graphql.EnumValueConfig{Value: models.BM},
			"BN": &graphql.EnumValueConfig{Value: models.BN},
			"BO": &graphql.EnumValueConfig{Value: models.BO},
			"BQ": &graphql.EnumValueConfig{Value: models.BQ},
			"BR": &graphql.EnumValueConfig{Value: models.BR},
			"BS": &graphql.EnumValueConfig{Value: models.BS},
			"BT": &graphql.EnumValueConfig{Value: models.BT},
			"BV": &graphql.EnumValueConfig{Value: models.BV},
			"BW": &graphql.EnumValueConfig{Value: models.BW},
			"BY": &graphql.EnumValueConfig{Value: models.BY},
			"BZ": &graphql.EnumValueConfig{Value: models.BZ},
			"CA": &graphql.EnumValueConfig{Value: models.CA},
			"CC": &graphql.EnumValueConfig{Value: models.CC},
			"CD": &graphql.EnumValueConfig{Value: models.CD},
			"CF": &graphql.EnumValueConfig{Value: models.CF},
			"CH": &graphql.EnumValueConfig{Value: models.CH},
			"CI": &graphql.EnumValueConfig{Value: models.CI},
			"CK": &graphql.EnumValueConfig{Value: models.CK},
			"CL": &graphql.EnumValueConfig{Value: models.CL},
			"CM": &graphql.EnumValueConfig{Value: models.CM},
			"CN": &graphql.EnumValueConfig{Value: models.CN},
			"CO": &graphql.EnumValueConfig{Value: models.CO},
			"CR": &graphql.EnumValueConfig{Value: models.CR},
			"CU": &graphql.EnumValueConfig{Value: models.CU},
			"CV": &graphql.EnumValueConfig{Value: models.CV},
			"CW": &graphql.EnumValueConfig{Value: models.CW},
			"CX": &graphql.EnumValueConfig{Value: models.CX},
			"CY": &graphql.EnumValueConfig{Value: models.CY},
			"CZ": &graphql.EnumValueConfig{Value: models.CZ},
			"DE": &graphql.EnumValueConfig{Value: models.DE},
			"DJ": &graphql.EnumValueConfig{Value: models.DJ},
			"DK": &graphql.EnumValueConfig{Value: models.DK},
			"DM": &graphql.EnumValueConfig{Value: models.DM},
			"DO": &graphql.EnumValueConfig{Value: models.DO},
			"DZ": &graphql.EnumValueConfig{Value: models.DZ},
			"EC": &graphql.EnumValueConfig{Value: models.EC},
			"EE": &graphql.EnumValueConfig{Value: models.EE},
			"EG": &graphql.EnumValueConfig{Value: models.EG},
			"EH": &graphql.EnumValueConfig{Value: models.EH},
			"ER": &graphql.EnumValueConfig{Value: models.ER},
			"ES": &graphql.EnumValueConfig{Value: models.ES},
			"ET": &graphql.EnumValueConfig{Value: models.ET},
			"FI": &graphql.EnumValueConfig{Value: models.FI},
			"FJ": &graphql.EnumValueConfig{Value: models.FJ},
			"FK": &graphql.EnumValueConfig{Value: models.FK},
			"FM": &graphql.EnumValueConfig{Value: models.FM},
			"FO": &graphql.EnumValueConfig{Value: models.FO},
			"FR": &graphql.EnumValueConfig{Value: models.FR},
			"GA": &graphql.EnumValueConfig{Value: models.GA},
			"GB": &graphql.EnumValueConfig{Value: models.GB},
			"GD": &graphql.EnumValueConfig{Value: models.GD},
			"GE": &graphql.EnumValueConfig{Value: models.GE},
			"GF": &graphql.EnumValueConfig{Value: models.GF},
			"GG": &graphql.EnumValueConfig{Value: models.GG},
			"GH": &graphql.EnumValueConfig{Value: models.GH},
			"GI": &graphql.EnumValueConfig{Value: models.GI},
			"GL": &graphql.EnumValueConfig{Value: models.GL},
			"GM": &graphql.EnumValueConfig{Value: models.GM},
			"GN": &graphql.EnumValueConfig{Value: models.GN},
			"GP": &graphql.EnumValueConfig{Value: models.GP},
			"GQ": &graphql.EnumValueConfig{Value: models.GQ},
			"GR": &graphql.EnumValueConfig{Value: models.GR},
			"GS": &graphql.EnumValueConfig{Value: models.GS},
			"GT": &graphql.EnumValueConfig{Value: models.GT},
			"GU": &graphql.EnumValueConfig{Value: models.GU},
			"GW": &graphql.EnumValueConfig{Value: models.GW},
			"GY": &graphql.EnumValueConfig{Value: models.GY},
			"HK": &graphql.EnumValueConfig{Value: models.HK},
			"HM": &graphql.EnumValueConfig{Value: models.HM},
			"HN": &graphql.EnumValueConfig{Value: models.HN},
			"HR": &graphql.EnumValueConfig{Value: models.HR},
			"HT": &graphql.EnumValueConfig{Value: models.HT},
			"HU": &graphql.EnumValueConfig{Value: models.HU},
			"ID": &graphql.EnumValueConfig{Value: models.ID},
			"IE": &graphql.EnumValueConfig{Value: models.IE},
			"IL": &graphql.EnumValueConfig{Value: models.IL},
			"IM": &graphql.EnumValueConfig{Value: models.IM},
			"IN": &graphql.EnumValueConfig{Value: models.IN},
			"IO": &graphql.EnumValueConfig{Value: models.IO},
			"IQ": &graphql.EnumValueConfig{Value: models.IQ},
			"IR": &graphql.EnumValueConfig{Value: models.IR},
			"IS": &graphql.EnumValueConfig{Value: models.IS},
			"IT": &graphql.EnumValueConfig{Value: models.IT},
			"JE": &graphql.EnumValueConfig{Value: models.JE},
			"JM": &graphql.EnumValueConfig{Value: models.JM},
			"JO": &graphql.EnumValueConfig{Value: models.JO},
			"JP": &graphql.EnumValueConfig{Value: models.JP},
			"KE": &graphql.EnumValueConfig{Value: models.KE},
			"KG": &graphql.EnumValueConfig{Value: models.KG},
			"KH": &graphql.EnumValueConfig{Value: models.KH},
			"KI": &graphql.EnumValueConfig{Value: models.KI},
			"KM": &graphql.EnumValueConfig{Value: models.KM},
			"KN": &graphql.EnumValueConfig{Value: models.KN},
			"KP": &graphql.EnumValueConfig{Value: models.KP},
			"KR": &graphql.EnumValueConfig{Value: models.KR},
			"KW": &graphql.EnumValueConfig{Value: models.KW},
			"KY": &graphql.EnumValueConfig{Value: models.KY},
			"KZ": &graphql.EnumValueConfig{Value: models.KZ},
			"LA": &graphql.EnumValueConfig{Value: models.LA},
			"LB": &graphql.EnumValueConfig{Value: models.LB},
			"LC": &graphql.EnumValueConfig{Value: models.LC},
			"LI": &graphql.EnumValueConfig{Value: models.LI},
			"LK": &graphql.EnumValueConfig{Value: models.LK},
			"LR": &graphql.EnumValueConfig{Value: models.LR},
			"LS": &graphql.EnumValueConfig{Value: models.LS},
			"LT": &graphql.EnumValueConfig{Value: models.LT},
			"LU": &graphql.EnumValueConfig{Value: models.LU},
			"LV": &graphql.EnumValueConfig{Value: models.LV},
			"LY": &graphql.EnumValueConfig{Value: models.LY},
			"MA": &graphql.EnumValueConfig{Value: models.MA},
			"MC": &graphql.EnumValueConfig{Value: models.MC},
			"MD": &graphql.EnumValueConfig{Value: models.MD},
			"ME": &graphql.EnumValueConfig{Value: models.ME},
			"MF": &graphql.EnumValueConfig{Value: models.MF},
			"MG": &graphql.EnumValueConfig{Value: models.MG},
			"MH": &graphql.EnumValueConfig{Value: models.MH},
			"MK": &graphql.EnumValueConfig{Value: models.MK},
			"ML": &graphql.EnumValueConfig{Value: models.ML},
			"MM": &graphql.EnumValueConfig{Value: models.MM},
			"MN": &graphql.EnumValueConfig{Value: models.MN},
			"MO": &graphql.EnumValueConfig{Value: models.MO},
			"MP": &graphql.EnumValueConfig{Value: models.MP},
			"MQ": &graphql.EnumValueConfig{Value: models.MQ},
			"MR": &graphql.EnumValueConfig{Value: models.MR},
			"MS": &graphql.EnumValueConfig{Value: models.MS},
			"MT": &graphql.EnumValueConfig{Value: models.MT},
			"MU": &graphql.EnumValueConfig{Value: models.MU},
			"MV": &graphql.EnumValueConfig{Value: models.MV},
			"MW": &graphql.EnumValueConfig{Value: models.MW},
			"MX": &graphql.EnumValueConfig{Value: models.MX},
			"MY": &graphql.EnumValueConfig{Value: models.MY},
			"MZ": &graphql.EnumValueConfig{Value: models.MZ},
			"NA": &graphql.EnumValueConfig{Value: models.NA},
			"NC": &graphql.EnumValueConfig{Value: models.NC},
			"NE": &graphql.EnumValueConfig{Value: models.NE},
			"NF": &graphql.EnumValueConfig{Value: models.NF},
			"NG": &graphql.EnumValueConfig{Value: models.NG},
			"NI": &graphql.EnumValueConfig{Value: models.NI},
			"NL": &graphql.EnumValueConfig{Value: models.NL},
			"NO": &graphql.EnumValueConfig{Value: models.NO},
			"NP": &graphql.EnumValueConfig{Value: models.NP},
			"NR": &graphql.EnumValueConfig{Value: models.NR},
			"NU": &graphql.EnumValueConfig{Value: models.NU},
			"NZ": &graphql.EnumValueConfig{Value: models.NZ},
			"OM": &graphql.EnumValueConfig{Value: models.OM},
			"PA": &graphql.EnumValueConfig{Value: models.PA},
			"PE": &graphql.EnumValueConfig{Value: models.PE},
			"PF": &graphql.EnumValueConfig{Value: models.PF},
			"PG": &graphql.EnumValueConfig{Value: models.PG},
			"PH": &graphql.EnumValueConfig{Value: models.PH},
			"PK": &graphql.EnumValueConfig{Value: models.PK},
			"PL": &graphql.EnumValueConfig{Value: models.PL},
			"PM": &graphql.EnumValueConfig{Value: models.PM},
			"PN": &graphql.EnumValueConfig{Value: models.PN},
			"PR": &graphql.EnumValueConfig{Value: models.PR},
			"PS": &graphql.EnumValueConfig{Value: models.PS},
			"PT": &graphql.EnumValueConfig{Value: models.PT},
			"PW": &graphql.EnumValueConfig{Value: models.PW},
			"PY": &graphql.EnumValueConfig{Value: models.PY},
			"QA": &graphql.EnumValueConfig{Value: models.QA},
			"RE": &graphql.EnumValueConfig{Value: models.RE},
			"RO": &graphql.EnumValueConfig{Value: models.RO},
			"RS": &graphql.EnumValueConfig{Value: models.RS},
			"RU": &graphql.EnumValueConfig{Value: models.RU},
			"RW": &graphql.EnumValueConfig{Value: models.RW},
			"SA": &graphql.EnumValueConfig{Value: models.SA},
			"SB": &graphql.EnumValueConfig{Value: models.SB},
			"SC": &graphql.EnumValueConfig{Value: models.SC},
			"SD": &graphql.EnumValueConfig{Value: models.SD},
			"SE": &graphql.EnumValueConfig{Value: models.SE},
			"SG": &graphql.EnumValueConfig{Value: models.SG},
			"SH": &graphql.EnumValueConfig{Value: models.SH},
			"SI": &graphql.EnumValueConfig{Value: models.SI},
			"SJ": &graphql.EnumValueConfig{Value: models.SJ},
			"SK": &graphql.EnumValueConfig{Value: models.SK},
			"SL": &graphql.EnumValueConfig{Value: models.SL},
			"SM": &graphql.EnumValueConfig{Value: models.SM},
			"SN": &graphql.EnumValueConfig{Value: models.SN},
			"SO": &graphql.EnumValueConfig{Value: models.SO},
			"SR": &graphql.EnumValueConfig{Value: models.SR},
			"SS": &graphql.EnumValueConfig{Value: models.SS},
			"ST": &graphql.EnumValueConfig{Value: models.ST},
			"SV": &graphql.EnumValueConfig{Value: models.SV},
			"SX": &graphql.EnumValueConfig{Value: models.SX},
			"SY": &graphql.EnumValueConfig{Value: models.SY},
			"SZ": &graphql.EnumValueConfig{Value: models.SZ},
			"TC": &graphql.EnumValueConfig{Value: models.TC},
			"TD": &graphql.EnumValueConfig{Value: models.TD},
			"TF": &graphql.EnumValueConfig{Value: models.TF},
			"TG": &graphql.EnumValueConfig{Value: models.TG},
			"TH": &graphql.EnumValueConfig{Value: models.TH},
			"TJ": &graphql.EnumValueConfig{Value: models.TJ},
			"TK": &graphql.EnumValueConfig{Value: models.TK},
			"TL": &graphql.EnumValueConfig{Value: models.TL},
			"TM": &graphql.EnumValueConfig{Value: models.TM},
			"TN": &graphql.EnumValueConfig{Value: models.TN},
			"TO": &graphql.EnumValueConfig{Value: models.TO},
			"TR": &graphql.EnumValueConfig{Value: models.TR},
			"TT": &graphql.EnumValueConfig{Value: models.TT},
			"TV": &graphql.EnumValueConfig{Value: models.TV},
			"TW": &graphql.EnumValueConfig{Value: models.TW},
			"TZ": &graphql.EnumValueConfig{Value: models.TZ},
			"UA": &graphql.EnumValueConfig{Value: models.UA},
			"UG": &graphql.EnumValueConfig{Value: models.UG},
			"UM": &graphql.EnumValueConfig{Value: models.UM},
			"US": &graphql.EnumValueConfig{Value: models.US},
			"UY": &graphql.EnumValueConfig{Value: models.UY},
			"UZ": &graphql.EnumValueConfig{Value: models.UZ},
			"VA": &graphql.EnumValueConfig{Value: models.VA},
			"VC": &graphql.EnumValueConfig{Value: models.VC},
			"VE": &graphql.EnumValueConfig{Value: models.VE},
			"VG": &graphql.EnumValueConfig{Value: models.VG},
			"VI": &graphql.EnumValueConfig{Value: models.VI},
			"VN": &graphql.EnumValueConfig{Value: models.VN},
			"VU": &graphql.EnumValueConfig{Value: models.VU},
			"WF": &graphql.EnumValueConfig{Value: models.WF},
			"WS": &graphql.EnumValueConfig{Value: models.WS},
			"YE": &graphql.EnumValueConfig{Value: models.YE},
			"YT": &graphql.EnumValueConfig{Value: models.YT},
			"ZA": &graphql.EnumValueConfig{Value: models.ZA},
			"ZM": &graphql.EnumValueConfig{Value: models.ZM},
			"ZW": &graphql.EnumValueConfig{Value: models.ZW},
		},
	},
)

var CountriesGraphQLType = graphql.NewObject(
	graphql.ObjectConfig{
		Name: "Country",
		Fields: graphql.Fields{
			"id": &graphql.Field{
				Name: "id",
				Type: graphql.String,
			},
			"code": &graphql.Field{
				Name: "code",
				Type: CountryCodeType,
			},
			"language": &graphql.Field{
				Name: "language",
				Type: graphql.String,
			},
			"region": &graphql.Field{
				Name: "region",
				Type: graphql.String,
			},
			"subregion": &graphql.Field{
				Name: "subregion",
				Type: graphql.String,
			},
			"capital": &graphql.Field{
				Name: "capital",
				Type: graphql.String,
			},
			"callingCode": &graphql.Field{
				Name: "callingCode",
				Type: graphql.String,
			},
			"flag": &graphql.Field{
				Name: "flag",
				Type: graphql.String,
			},
			"flagEmoji": &graphql.Field{
				Name: "flagEmoji",
				Type: graphql.String,
			},
		},
	})
